baseURL = 'https://olivergilan.com/'
languageCode = 'en-us'
title = 'Oliver Gilan'
sectionPagesMenu = "main"
pluralizelisttitles = false
disableKinds = ['taxonomy', 'term']

copyright = "2022 Oliver Gilan All rights reserved"
[author]
	name = "Oliver Gilan"
	email = "blog@olivergilan.com"

[menu]
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog/"

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/olivergilan"
    [menu.main.params]
        targetBlank = true

[[menu.socials]]
    identifier = "github"
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/olivergilan"
    [menu.socials.params]
        targetBlank = true
        icon = "/icons/github.png"

[[menu.socials]]
    identifier = "linkedin"
    name = "LinkedIn"
    title = "LinkedIn"
    url = "https://linkedin.com/in/oliver-gilan/"
    [menu.socials.params]
        targetBlank = true
        icon = "/icons/linkedin.png"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 4

[markup.goldmark.renderer]
unsafe= true