baseURL = 'https://olivergilan.com/'
languageCode = 'en-us'
title = 'Oliver Gilan'
sectionPagesMenu = "main"
pluralizelisttitles = false

[menu]
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog/"

[[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/olivergilan"
    [menu.main.params]
        targetBlank = true