baseURL = 'https://olivergilan.com/'
languageCode = 'en-us'
title = 'Oliver Gilan'
sectionPagesMenu = "main"
pluralizelisttitles = false
disableKinds = ['taxonomy', 'term']
relativeURLs = "True"

copyright = "2022 Oliver Gilan All rights reserved"
[author]
	name = "Oliver Gilan"
	email = "blog@olivergilan.com"

[outputFormats]
    [outputFormats.RSS]
        mediatype = "application/rss"
        baseName = "rss"

[menu]
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog/"

[[menu.main]]
    identifier = "stream"
    name = "Stream"
    title = "Stream"
    url = "/stream/"

[[menu.main]]
    identifier = "blogroll"
    name = "Blogroll"
    title = "Blogroll"
    url = "/blogroll/"

[[menu.main]]
    identifier = "books"
    name = "Reading List"
    title = "Reading List"
    url = "/books/"

[[menu.main]]
    identifier = "rss"
    name = "RSS"
    title = "RSS"
    url = "https://olivergilan.com/index.xml"
    [menu.main.params]
        targetBlank = true
        icon = "/icons/rss-fa.svg"

[[menu.socials]]
    identifier = "github"
    name = "GitHub"
    title = "GitHub"
    url = "https://github.com/olivergilan"
    [menu.socials.params]
        targetBlank = true
        icon = "/icons/github-fa.svg"

[[menu.socials]]
    identifier = "linkedin"
    name = "LinkedIn"
    title = "LinkedIn"
    url = "https://linkedin.com/in/oliver-gilan/"
    [menu.socials.params]
        targetBlank = true
        icon = "/icons/linkedin-fa.svg"

[[menu.socials]]
    identifier = "twitter"
    name = "Twitter"
    title = "Twitter"
    url = "https://twitter.com/olvrgln"
    [menu.socials.params]
        targetBlank = true
        icon = "/icons/email-fa.svg"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'github'
    tabWidth = 4

[markup.goldmark.renderer]
unsafe= true